export const INTEGRATED = 'INTEGRATED';
export const WINDOWED = 'WINDOWED';
export const CHAT_IS_INTEGRATED = 'CHAT INTEGRATED = TRUE';
export const CHAT_IS_NOT_INTEGRATED = 'CHAT INTEGRATED = FALSE';
